 version: '3.8'
 services:
    postgres:
      image: postgres:15
      container_name: postgres-tareas
      ports:
        - "5432:5432"
      environment:
        POSTGRES_DB: tareasdb
        POSTGRES_USER: tareasuser
        POSTGRES_PASSWORD: tareaspwd
      volumes:
        - postgres-data:/var/lib/postgresql/data
        
 volumes:
    postgres-data: